{
 "title": "Timescale NFT Analysis - Collections",
 "description": "Dashboard to analyze an NFT collection from OpenSea",
 "time": { "from": "2021-09-30T04:00:00.000Z", "to": "2021-10-08T03:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "collection",
    "label": "Collection Name",
    "query": "SELECT slug from collections LIMIT 100;"
   }
  ]
 },
 "panels": [
  {
   "title": "Single collection stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily total sales for $collection",
     "type": "timeseries",
     "description": "Daily total number of sales for assets in $collection",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  bucket AS \"time\",\n  slug, volume\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nWHERE slug IN ('$collection')\n  AND $__timeFilter(bucket) \nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Daily ETH volume for $collection",
     "type": "timeseries",
     "description": "Daily total of ETH spent on purchasing assets in the $collection collection",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  bucket AS \"time\",\n  slug, volume_eth\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nWHERE slug IN ('$collection')\n  AND $__timeFilter(bucket) \nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Price of most expensive items sold in $collection",
     "type": "timeseries",
     "description": "Price in ETH of the most expensive NFT sold in $collection collection",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  bucket AS \"time\", slug, max_price AS \"price_ETH\"\n  --most_expensive_nft AS most_expensive_nft_id\n  --, name AS most_expensive_nft_name\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nINNER JOIN assets a on a.id = cagg.most_expensive_nft_id\nWHERE slug IN ('$collection')\n  AND $__timeFilter(bucket) \nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Mean vs Median Price of Asset in $collection",
     "type": "timeseries",
     "description": "Daily chart of mean vs median price of an asset sold in $collection",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  bucket AS \"time\",\n  slug, mean_price, median_price\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nWHERE slug IN ('$collection')\n  AND $__timeFilter(bucket) \nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Most expensive items sold during time period in $collection",
     "type": "table",
     "description": "Name and price in ETH of the most expensive NFT sold in $collection collection for time period selected",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT bucket AS \"time\", a.name as \"nft name\", max_price AS \"price_ETH\", a.url AS \"url\"\n  --most_expensive_nft AS most_expensive_nft_id\n  --, name AS most_expensive_nft_name\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nINNER JOIN assets a on a.id = cagg.most_expensive_nft_id\nWHERE slug IN ('$collection')\n  AND $__timeFilter(bucket) \nORDER BY 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Simple queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 highest sale volume collections",
     "type": "table",
     "description": "Collections with highest sale volume",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT \nslug,\nSUM(volume) total_volume,\nSUM(volume_eth) total_volume_eth\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nINNER JOIN assets a ON a.id = cagg.most_expensive_nft_id\nGROUP BY cagg.collection_id, slug\nORDER BY total_volume DESC\nLIMIT 20;"
      }
     ]
    },
    {
     "title": "Top 20 highest ETH volume collections",
     "type": "barchart",
     "description": "Collections with highest sale volume",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT \nslug,\nSUM(volume) total_volume\n-- SUM(volume_eth) total_volume_eth\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nINNER JOIN assets a ON a.id = cagg.most_expensive_nft_id\nGROUP BY cagg.collection_id, slug\nORDER BY total_volume DESC\nLIMIT 20;"
      }
     ]
    },
    {
     "title": "Top 20 highest ETH volume collections",
     "type": "table",
     "description": "Collections with highest ETH volume",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT \nslug,\nSUM(volume_eth) total_volume_eth,\nSUM(volume) total_volume\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nINNER JOIN assets a ON a.id = cagg.most_expensive_nft_id\nGROUP BY cagg.collection_id, slug\nORDER BY total_volume_eth DESC\nLIMIT 20;"
      }
     ]
    },
    {
     "title": "Daily sales of Cryptokitties",
     "type": "timeseries",
     "description": "Daily sales of NFTs in the CryptoKitties collection",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  bucket AS \"time\",\n  slug, volume\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nWHERE\n  $__timeFilter(bucket) AND slug = 'cryptokitties'\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Daily sales of multiple NFT collections",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\n  bucket AS \"time\",\n  slug, volume\nFROM collections_daily cagg\nINNER JOIN collections c ON cagg.collection_id = c.id\nWHERE\n  $__timeFilter(bucket) AND slug IN ('cryptokitties', 'lazy-lions', 'afrodroids-by-owo')\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Snoop Dogg's NFT Activity",
     "type": "table",
     "description": "Trading Activity of Snoop Dogg for time-period chosen",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "WITH snoop_dogg AS (\n    SELECT id FROM accounts\n    WHERE address = '0xce90a7949bb78892f159f428d0dc23a8e3584d75'\n)\nSELECT\nCOUNT(*) AS trade_count,\nCOUNT(DISTINCT asset_id) AS nft_count,\nCOUNT(DISTINCT collection_id) AS collection_count,\nCOUNT(*) FILTER (WHERE seller_account = (SELECT id FROM snoop_dogg)) AS sale_count,\nCOUNT(*) FILTER (WHERE winner_account = (SELECT id FROM snoop_dogg)) AS buy_count,\nSUM(total_price) AS total_volume_eth,\nAVG(total_price) AS avg_price,\nMIN(total_price) AS min_price,\nMAX(total_price) AS max_price\nFROM nft_sales\nWHERE payment_symbol = 'ETH' AND ( seller_account = (SELECT id FROM snoop_dogg) OR winner_account = (SELECT id FROM snoop_dogg) )\nAND time > NOW()-INTERVAL '3 months'"
      }
     ]
    }
   ]
  }
 ]
}