{
 "title": "NFT sales",
 "time": { "from": "2020-12-31T23:00:00.000Z", "to": "2021-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "collection_slug",
    "label": "Collection slug",
    "query": "SELECT slug FROM (\n\tSELECT collection_id FROM one_week_collections\n\tGROUP BY collection_id\n) s \nINNER JOIN collections c ON c.id = s.collection_id"
   },
   {
    "name": "collection_id",
    "label": "Collection ID",
    "query": "SELECT id FROM collections WHERE slug IN ('$collection_slug');"
   },
   {
    "name": "cagg",
    "label": "Time bucket",
    "query": "one_day_collections, one_week_collections, polygon_one_day, polygon_one_week, one_day_eth, one_week_eth, one_month_eth"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT details->>'created_date' AS Created, name, details->>'image_url' AS image, slug, url as OpenSea, \n        details->>'discord_url' AS Discord,\n        details->>'external_url' AS Web,\n        'https://twitter.com/' || (details->>'twitter_username') AS Twitter\n        FROM collections\nWHERE\n  id = $collection_id"
    }
   ]
  },
  {
   "title": "Most expensive assets sold",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n cagg.bucket as time,\n details->>'image_url',\n a.name,\n cagg.max_price || ' ETH' as price,\n a.url\nFROM ${cagg:raw} cagg\nINNER JOIN assets a ON a.id = cagg.most_expensive_nft_id \nWHERE\n  $__timeFilter(\"bucket\") AND\n  cagg.collection_id = $collection_id\nORDER BY max_price DESC \nLIMIT 20"
    }
   ]
  },
  {
   "title": "Most recent trades",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT time, details->>'image_url' AS image_url, a.\"name\" AS asset,\n total_price || ' ETH' as price, a.url FROM nft_sales s\nINNER JOIN assets a ON a.id = s.asset_id\nWHERE\n  $__timeFilter(\"time\") AND\n  s.collection_id = $collection_id\nORDER BY time DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Volume in ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  volume_eth\nFROM ${cagg:raw}\nWHERE\n  $__timeFilter(bucket) AND\n  collection_id = $collection_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of trades",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  volume\nFROM ${cagg:raw}\nWHERE\n  $__timeFilter(bucket) AND\n  collection_id = $collection_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mean and median price in ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  mean_price,\n  median_price\nFROM ${cagg:raw}\nWHERE\n  $__timeFilter(bucket) AND\n  collection_id = $collection_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Max price in ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  max_price\nFROM ${cagg:raw}\nWHERE\n  $__timeFilter(bucket) AND\n  collection_id = $collection_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of unique buyers (approximately)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  distinct_count(winner_hyperloglog) as buyers\nFROM ${cagg:raw}\nWHERE\n  $__timeFilter(bucket) AND\n  collection_id = $collection_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of unique sellers (approximately)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  distinct_count(seller_hyperloglog) as sellers\nFROM ${cagg:raw}\nWHERE\n  $__timeFilter(bucket) AND\n  collection_id = $collection_id\nORDER BY 1"
    }
   ]
  }
 ]
}